[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "pycryptodome>=3.22.0",
    "pyrebase4>=4.8.0",
    "pyrebase>=3.0.18",
    "streamlit>=1.43.2",
]
